Feat/hotstuff phase (#1)
* Add hotstuff folder

* Fix getrandom issue

* Fix error[E0583]: file not found for module `sys`

* Fix build error

* Add hotstuff vote module

* Add BlockProducer

* Fix missing use

* Add FinalityBlock

* Update hotstuff lib test

* Add HotstuffVotingSystem

* Add sp_consensus_hotstuff modules

* Rename Hotstuff VoteInfo to VoteMessage

* Add signature field for VoteMessage

* Add VoteMessage signature validation

* Update hotstuff folder, split files

* Add hotstuff qc file

* Update hotstuff folder structure

* Update sc consensus hotstuff, replace aura

* Add debug log

* Add client grandpa module

* Add hotstuff network bridge file

* Add HotstuffBlockImport module

* Update hotstuff block import

* Update node/services.rs

* Update hotstuff node/service.rs

* Fix hotstuff AuthoritySet module runtime panic issue

* Add run_hotstuff_voter entry function

* Update hotstuff import and voter task

* finalize block

* update chain spec
remove unused log

* correctly exit voter task future

* remove unused code

* 1.Deduplication of future tasks
2.Adjust log

* Fix warning issue

* simpleVoter get block author

* remove unused

* improve log

* remove unused

* Update block author conditional judgment

* local peer id

* Update gossip message

* Update SimpleVoter, reconstructed function

* cargo fmt

* hotstuff consensus messages

* fix compile

* hotstuff QC unit tests

* fix unit tests

* hotstuff messages

* simple kv store

* fix compile

* basic hotstuff components

* hotstuff consensus phase

* remove unused code

* node use hotstuff consensus

* remove unused code

* update chain spec

* hotstuff just use sr25519

* remove unused code

* add debug info

* hotstuff phase draft

* improve debug info

---------

Co-authored-by: codemax <codemax@gmail.com>
Co-authored-by: sunjiaxing <15215616197@163.com>
Co-authored-by: codingcat <istommao@gmail.com>
Co-authored-by: sjxqqq <45069936+sjxqqq@users.noreply.github.com>
Co-authored-by: sjxqqq <312735767@qq.com>
Co-authored-by: jerrybaoo <shirui_yjj133@163.com>